blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/unchainedshop/unchained/discussions/categories/q-a
    about: Ask questions and get help from the community
  - name: Feature Ideas
    url: https://github.com/unchainedshop/unchained/discussions/categories/ideas
    about: Share and discuss ideas for new features
  - name: Documentation
    url: https://docs.unchained.shop
    about: Check our documentation for guides and API reference
